data:
  features: ./datasets/features.txt
  path: ./perio_data_sherlockperio_data_sherlockTNFa_Granulocytes_(CD45-CD66+)_train.h5ad
  condition: drug
  source: Unstim
  type: cell

dataloader:
  batch_size: 256
  shuffle: true

datasplit:
  groupby: drug
  name: train_test
  test_size: 0.2
