data:
  features: ./datasets/atest_data/features.txt
  path: ./datasets/atest_data/combined_Bcell3.h5ad
  condition: drug
  source: Unstim_Bcell
  type: cell

dataloader:
  batch_size: 256
  shuffle: true

datasplit:
  groupby: drug
  name: train_test
  test_size: 0.2
